### ISSUE TITLE
Illegal reflective access warning

### ISSUE THREAD

**Issue by hannah-sains** [pjfanning/excel-streaming-reader#62]
When using `StreamingReader` to open our file, we are seeing the following warnings:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.github.pjfanning.xlsx.XmlUtils (file:/Users/username/.m2/repository/com/github/pjfanning/excel-streaming-reader/2.0.0/excel-streaming-reader-2.0.0.jar) to method com.sun.org.apache.xerces.internal.util.SecurityManager.setEntityExpansionLimit(int)
WARNING: Please consider reporting this to the maintainers of com.github.pjfanning.xlsx.XmlUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Code causing warning:
```
val workBook = StreamingReader.builder()
            .rowCacheSize(1000)
            .bufferSize(4096)
            .open(fileInputStream)
```

Would be good to fix to ensure it isn't denied in future releases 👍

**Comment by pjfanning** [comment]
I'm not sure what version you are using but there is no reflection code in excel-streaming-reader any more (latest code in main branch) - we do rely on Apache POI code like XMLHelper/DocumentHelper and they do rely on Java reflection. If you want Apache POI to fix the issue then you'll need to raise an issue with them.

Right now, it makes sense to use reflection (in POI code) because they don't want to force you to use a particular XML parser but they want to configure the parser to stop XML exploits like XML Entity Expansion attacks - and despite the warnings, reflection is still supported in all Java releases to date.
